In [1]:
import numpy as np

In [24]:
l1=np.array([[1,2,3],[4,5,6]])
l2=np.array([1,2,3])
print(l1+l2)
l1[-1][-1]
l3=np.array(((1,2,3),(4,5,6)))
l_new=l1[0]
l_new[1]=999
print(l_new)
print(l1)

[[2 4 6]
 [5 7 9]]
[  1 999   3]
[[  1 999   3]
 [  4   5   6]]


In [56]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[0,1],[2,3]])
arr1.shape

(3, 2)

In [88]:
arr1=np.arange(12).reshape(4,3)
# arr1
a=np.delete(arr1,1,1)
print(arr1)
a

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [77]:
l1=np.array([1,2,3,4,5,6,7,8,9])
l2=np.copy(l1[1:2])
l2[0]=3
l1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
from scipy import stats
mean=40
sd=2
x = np.random.normal(loc=mean, scale=sd, size=1000)
stats.mode(x)

ModeResult(mode=array([33.4962078]), count=array([1]))