In [16]:
#Univariate
#Using sklearn with own data
#np.array used as an input
from sklearn import linear_model
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
x=x.reshape(-1,1)
y=np.array([1,4,9,16,25,36,49,64,81,100])
y=y.reshape(-1,1)

In [18]:
# xtrain=x[0:-2]
# xtest=x[-2:]
# ytrain=y[0:-2]
# ytest=y[-2:]
xtrain=x
xtest=x
ytrain=y
ytest=y
print("X TRAINING")
print(xtrain)
print("X TESTING")
print(xtest)
print("Y TRAINING")
print(ytrain)
print("Y TESTING")
print(ytest)

X TRAINING
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
X TESTING
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Y TRAINING
[[  1]
 [  4]
 [  9]
 [ 16]
 [ 25]
 [ 36]
 [ 49]
 [ 64]
 [ 81]
 [100]]
Y TESTING
[[  1]
 [  4]
 [  9]
 [ 16]
 [ 25]
 [ 36]
 [ 49]
 [ 64]
 [ 81]
 [100]]


In [27]:
# Fitting Multi Linear regression model to training model 
from sklearn.linear_model import LinearRegression 
regressor = LinearRegression() 
regressor.fit(xtrain, ytrain) 
   
# predicting the test set results 
y_pred = regressor.predict(xtest) 
y_pred = y_pred.reshape(-1,1) 
print("\n   RESULT OF LINEAR REGRESSION PREDICTION : ") 
print ("\nPredicted : \n", y_pred[:, :]) 
error_sq=(y-y_pred)**2
mse=error_sq.mean()
mse


   RESULT OF LINEAR REGRESSION PREDICTION : 

Predicted : 
 [[-1.10000000e+01]
 [ 1.42108547e-14]
 [ 1.10000000e+01]
 [ 2.20000000e+01]
 [ 3.30000000e+01]
 [ 4.40000000e+01]
 [ 5.50000000e+01]
 [ 6.60000000e+01]
 [ 7.70000000e+01]
 [ 8.80000000e+01]]


52.799999999999955